apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- ingress.yml
- service.yml

namespace: remmen-website-redesign

images:
- name: DUMMY_IMAGE
  newName: harbor.herren5.ch/remmen/website
  newTag: 599_main
