stages:
   - build

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"

image: earthly/earthly:v0.7.12

before_script:
    - earthly bootstrap
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY

earthly:
  stage: build
  script:
    - earthly --ci --push -P +container --tag="${CI_PIPELINE_ID}_${CI_COMMIT_REF_NAME}"