stages:
   - build

services:
  - docker:20.10.16-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"

image: earthly/earthly:v0.7.12

before_script:
    - earthly bootstrap
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY

earthly:
  stage: build
  script:
    - earthly --ci --push -P +container --tag="${CI_PIPELINE_ID}_${CI_COMMIT_REF_NAME}"