stages:
   - build
   - deploy
   - commit_to_git

services:
  - docker:20.10.16-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"

earthly:
  stage: build
  image: earthly/earthly:v0.7.12

  before_script:
      - earthly bootstrap
      - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
  script:
    - earthly --ci --push -P +container --tag="${CI_PIPELINE_ID}_${CI_COMMIT_REF_NAME}" --registry="$REGISTRY"


deploy:
  stage: deploy
  image: remmenio/ci-toolkit
  script: 
    - |
      cd deploy/$CI_COMMIT_REF_NAME
      kustomize edit set image DUMMY_IMAGE=$REGISTRY/remmen/redesign:$CI_PIPELINE_ID_$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - deploy/$CI_COMMIT_REF_NAME/kustomization.yaml

git_push:
  stage: commit_to_git
  image: remmenio/ci-toolkit
  tags:
    - docker
  script: 
    - |
      git config --global user.email "foo@bar.ch"
      git config --global user.name "foobar"
      git add deploy/$CI_COMMIT_REF_NAME/kustomization.yaml
      git commit -m "Updated version number from  $CI_COMMIT_SHORT_SHA [skip ci]"
      git push -o ci-skip https://foobar:${GIT_TOKEN}@gitlab.herren5.ch/websites/remmen_redesign.git HEAD:$CI_COMMIT_REF_NAME
    